// Hotlinked GIFs shown after the uploaded items in the gallery.
const T = "https://media.tenor.com/";
export default [
  { src: T + "8JhcC4OtwC8AAAAM/hatsune-miku-dance.gif", caption: "Miku" },
  { src: T + "0MnUWg3WxscAAAAM/miku-hatsunemiku-sekai-sekaiiiiide-sekaide-hatsune.gif", caption: "Miku" },
  { src: T + "dZ62aSShMnsAAAAM/miku-hatsune-miku.gif", caption: "Miku" },
  { src: T + "35-Atzd35kMAAAAM/kasane-teto-adorable.gif", caption: "Teto" },
  { src: T + "ccvCZ_4wu5cAAAAM/kasane-teto-utau.gif", caption: "Teto" },
  { src: T + "dx27auDEUOkAAAAM/teto-vocaloid.gif", caption: "Teto" },
  { src: T + "aa2hE8nhMh4AAAAM/bye-freddy-fazbear.gif", caption: "FNAF" },
  { src: T + "0-s-9KOw68MAAAAM/five-nights-at-freddy%27s-foxy.gif", caption: "FNAF" },
  { src: T + "Azgs7QZoYdwAAAAM/fnaf-scary.gif", caption: "FNAF" },
  { src: T + "7ntol4KKaZYAAAAM/mob-dimple.gif", caption: "Mob Psycho 100" },
  { src: T + "3HIePffvJIgAAAAM/reigen-arataka-mob-psycho-100.gif", caption: "Mob Psycho 100" },
  { src: T + "AsTrA5cKBZMAAAAM/frieren-crying.gif", caption: "Frieren" },
  { src: T + "FkELNdTE-l8AAAAM/frieren-sip-frieren.gif", caption: "Frieren" },
  { src: T + "6YdH9_jC3AMAAAAM/bocchi.gif", caption: "Bocchi the Rock" },
  { src: T + "4emuSWvm6MoAAAAM/ryo-yamada-bocchi-the-rock.gif", caption: "Bocchi the Rock" },
  { src: T + "184Yhh8K-XAAAAAM/kaguya-shinomiya-kaguya-sama.gif", caption: "Kaguya-sama" },
  { src: T + "3jVWXtXA7jQAAAAM/anya-spy-x-family.gif", caption: "Spy x Family" },
  { src: T + "IHorQyQ_1yUAAAAM/cowboy-bebop.gif", caption: "Cowboy Bebop" },
  { src: T + "F2oy742HqqgAAAAM/josuke.gif", caption: "JoJo" },
  { src: T + "8GdzYHfBgHMAAAAM/nezuko-tanjiro.gif", caption: "Demon Slayer" },
  { src: T + "6ftWUtjeBfQAAAAM/luffy.gif", caption: "One Piece" },
  { src: T + "7xXVBt_dMhgAAAAM/naruto.gif", caption: "Naruto" },
];
